version: '3'
services:
  craw:
    build:
      context: .
      dockerfile: Craw/CrawDockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.env:/app/.env:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - craw
    environment:
      - CRAWING_TARGET=KQXSVN,KQXSVNFirstSpecial
      - CRAWING_START_DATE=2019-06-03
      #- CRAWING_END_DATE=2019-07-03

networks:
  craw:
    driver: bridge
