version: '3'
services:
  web:
    build:
      context: .
      dockerfile: FlaskDockerfile
    restart: always
    ports:
      - 80:5000
      - 443:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
      - .env:/app/.env:ro
    environment:
      - FLASK_ENV=production
