version: '3'
services:
  web:
    build:
      context: .
      dockerfile: FlaskDockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
      - .env:/app/.env:ro
    environment:
      - FLASK_ENV=production
