version: '3'
services:
  web:
    build:
      context: .
      dockerfile: FlaskApp/FlaskDockerfile
    restart: always
    ports:
      - 80:5000
      - 443:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .env:/app/.env:ro
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    networks:
      - web

networks:
  web:
    driver: bridge
