version: '3'
services:
  tele:
    build:
      context: .
      dockerfile: Tele/TeleDockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .envcp:/app/.env:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
      - ./Utils/LotteryAi.py:/app/Utils/LotteryAi.py:ro
    environment:
      - STORE_DIR=/app/crawing-data/xosobinhduong
      - MODEL_DIR=/app/models
      - PREDICTION_NUMBER=1
    networks:
      - tele

networks:
  tele:
    driver: bridge

