version: '3'
services:
  tele:
    build:
      context: .
      dockerfile: TeleDockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .env:/app/.env:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
