version: '3'
services:
  tele:
    build:
      context: .
      dockerfile: Tele/TeleDockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .envcp:/app/.env:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
    networks:
      - tele

networks:
  tele:
    driver: bridge

