version: '3'
services:
  train:
    build:
      context: .
      dockerfile: TrainDockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./models:/app/models
      - ./crawing-data:/app/crawing-data
      - ./data:/app/data
    environment:
      - CHANELS=an-giang,binh-thuan,vinh-long,binh-duong,tra-vinh,tp-hcm,long-an,binh-phuoc,hau-giang,vietlot-655
